# Generated by Django 4.2.6 on 2023-12-14 07:10

from django.db import migrations, models
import django.db.models.deletion
import telemarketing_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('telemarketing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID аккаунта')),
                ('doc_name', models.TextField(verbose_name='Ограничения')),
                ('doc_type', models.TextField(verbose_name='Пакет услуг')),
                ('doc_date', models.DateField(verbose_name='Дата создания аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунты',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID клиента')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, null=True, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('id_passport', models.IntegerField(blank=True, null=True, verbose_name='Номер и серия паспорта')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('phone_number', models.TextField(validators=[telemarketing_app.models.validate_phone_number], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id_work', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID встречи')),
                ('work_status', models.CharField(validators=[telemarketing_app.models.status_validator], verbose_name='Результат встречи\n(Успешно, Неуспешно)')),
            ],
            options={
                'verbose_name': 'Встречи',
                'verbose_name_plural': 'Встречи',
                'db_table': 'work',
            },
        ),
        migrations.RemoveField(
            model_name='trud',
            name='id_department',
        ),
        migrations.RemoveField(
            model_name='trud',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_doc',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Trud',
        ),
        migrations.AddField(
            model_name='work',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telemarketing_app.employee', verbose_name='ID Сотрудника'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='telemarketing_app.client', verbose_name='ID клиента'),
        ),
    ]
